In [92]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [93]:
clf = RandomForestClassifier(random_state = 0)

In [94]:
par = {'n_estimators' : range(10,51,10) , 'max_depth' : range(1,13,2) , 'min_samples_leaf' : range(1,8)\
       , 'min_samples_split' : range(2,10,2)}

In [95]:
searcher = GridSearchCV(clf,par,cv = 3,n_jobs=-1)

In [96]:
test = pd.read_csv('/Users/artemarhipov/Downloads/testing_mush.csv')
data = pd.read_csv('/Users/artemarhipov/Downloads/training_mush.csv')

In [97]:
data.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,class
0,2,0,3,1,5,1,0,0,9,1,...,3,7,0,2,1,4,3,5,0,0
1,2,0,4,0,5,1,0,1,10,0,...,7,4,0,2,1,0,7,4,0,1
2,2,0,3,0,2,1,0,0,7,0,...,0,4,0,2,1,2,1,5,1,1
3,0,0,3,0,5,1,1,0,2,0,...,7,7,0,2,2,4,7,3,1,0
4,2,3,3,1,5,1,0,0,10,1,...,3,6,0,2,1,4,2,5,0,0

In [98]:
searcher.fit(data.drop('class',axis = 1), data['class'])

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=0), n_jobs=-1,
             param_grid={'max_depth': range(1, 13, 2),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 10, 2),
                         'n_estimators': range(10, 51, 10)})

In [99]:
searcher.best_params_

{'max_depth': 9,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 10}

In [100]:
clf = searcher.best_estimator_

In [101]:
xes = data.columns

In [102]:
xes

Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat', 'class'],
      dtype='object')

In [103]:
f = pd.DataFrame({'imp' :pd.Series(clf.feature_importances_), 'fea': pd.Series(xes)})

In [104]:
f.sort_values('imp')

         imp                       fea
5   0.000000           gill-attachment
15  0.000000                 veil-type
0   0.002577                 cap-shape
1   0.003130               cap-surface
14  0.006253    stalk-color-below-ring
9   0.007563               stalk-shape
16  0.010881                veil-color
17  0.013910               ring-number
13  0.017689    stalk-color-above-ring
2   0.021773                 cap-color
21  0.022611                   habitat
11  0.031802  stalk-surface-above-ring
20  0.043783                population
12  0.048296  stalk-surface-below-ring
7   0.068461                 gill-size
3   0.070109                   bruises
18  0.070726                 ring-type
6   0.080840              gill-spacing
19  0.083564         spore-print-color
10  0.103793                stalk-root
8   0.103861                gill-color
4   0.188376                      odor
22       NaN                     class

In [105]:
pr = pd.DataFrame({'predicted' : clf.predict(data.drop('class',axis = 1))})
pr

      predicted
0             0
1             1
2             1
3             0
4             0
...         ...
6088          0
6089          1
6090          1
6091          0
6092          1

[6093 rows x 1 columns]

In [106]:
pr[pr.predicted == 1]

      predicted
1             1
2             1
5             1
6             1
7             1
...         ...
6086          1
6087          1
6089          1
6090          1
6092          1

[2940 rows x 1 columns]

In [109]:
pd.Series(clf.predict(test)).value_counts()

0    1055
1     976
dtype: int64